[package]
name = "ffrostfall/bridgenet2"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "The successor to BridgeNet, BridgeNet2 is a blazing-fast networking library designed for scale and performance."
license = "MIT"

[dependencies]
RemotePacketSizeCounter = "pysephwasntavailable/remotepacketsizecounter@2.1.0"
signal = "ffrostfall/luausignal@0.2.1"
